name: Dependency Review
on: # yamllint disable-line rule:truthy
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '*/spec/fixtures/**'
      - '*/helpers/test/*/fixtures/**'
      - 'common/lib/dependabot.rb'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Perform Dependency Review
        uses: actions/dependency-review-action@bc41886e18ea39df68b1b1245f4184881938e050 # v4.7.2
